// <auto-generated />
namespace MVC_EF_SQLSERVE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201806102151 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201806102151));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101351330_201806102151"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
